[package]
name = "connectors-sdk"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4.22"
bytes = "1.9.0"
prost = "0.13.3"
chrono = "0.4.38"
futures = "0.3.31"
async-nats = "0.38.0"
tokio = { version = "1.41.1", features = ["full"] }

protocol = "0.1.0"