name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Protocol Buffers Compiler (protoc)
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Build the stack
    
      run: docker-compose -f nats-compose.yml up -d
    - name: Run tests
    
      run: cargo test --verbose
